### ISSUE TITLE
return_avail_cost design problem

### ISSUE THREAD

**Issue by maxcaseylin** [anticardgamecardgameclub/dominion#21]
A lot of the return_avail_cost methods started out as Game associated methods. However effects_on_play doesn't take &Game type, so we aren't able to use return_avail_cost. We can make return_avail_... methods static, but they'd have to be in a separate mod, but that causes unnecessary complexity.

**Comment by Chenkail** [comment]
No longer an issue after refactoring turn-related methods to be part of Game
